# Generated by Django 4.1.3 on 2022-12-17 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_seller_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('p_no', models.BigIntegerField()),
                ('upload', models.ImageField(default='', upload_to='product/')),
                ('price', models.FloatField()),
                ('stock', models.BigIntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller')),
            ],
        ),
    ]
