# Generated by Django 4.1.3 on 2022-12-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.ImageField(upload_to=''),
        ),
    ]
