# Generated by Django 4.1.3 on 2022-12-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(default='', max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('company_name', models.CharField(max_length=50)),
                ('acc_holder_name', models.CharField(max_length=50)),
                ('ifsc', models.CharField(default='', max_length=25)),
                ('branch', models.CharField(max_length=50)),
                ('acc_no', models.BigIntegerField()),
                ('upload', models.ImageField(default='', upload_to='seller/')),
                ('user_name', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
